### ISSUE TITLE
Allow GraphServiceClient to be set

### ISSUE THREAD

**Issue by KennethScott** [ESC-BV/FluentEmail.Graph#142]
Have you ever considered allowing the GraphServiceClient to be passed in, as opposed to instantiating it automatically in the constructor of GraphSender?    I already use Graph for other things via an IConfidentialClientApplication to manage the auth token for the GraphServiceClient, so I basically keep an authenticated client ready to go as needed.  It'd be nice to just add the extra scope and reference it instead of having a separate client spun up.  Then I also wouldn't have references to the tenantid/clientid/clientsecret in two places.  Maybe allow it to be passed in, but still default it or something?  Just curious as to your thoughts.  Thanks-

**Comment by matt-goldman** [comment]
Not a bad idea @KennethScott. There are already two versions of the `AddGraphSender` method with different signatures, no reason you couldn't add another. Might also be nice to have another option that resolves the GraphServiceClient from DI, you could do this using ActivatorUtilities.

**Comment by DavidDeSloovere** [comment]
Thanks @KennethScott - just published a new version with the merge:
https://www.nuget.org/packages/FluentEmail.Graph/2.1.0

I'm ok with just this extra AddGraphSender overload for now.
I took the AddGraphSender method from the original code (and the pattern is also used in the other FluentEmail libs).
Personally, I would also prefer a more DI approach though.
