### ISSUE TITLE
Mail Headers

### ISSUE THREAD

**Issue by PS2009DT** [ESC-BV/FluentEmail.Graph#158]
Hi, just a quick note, we appear to be missing to set mail headers. Other senders are setting these but not graph sender.

Would you be able to add the same?

**Comment by DavidDeSloovere** [comment]
Didn't know that was an option in other sender. Could you point me to the code in the other senders so I can have a look?

**Comment by PS2009DT** [comment]
Sure! Thanks for the prompt reply.

Example on headers in SMTPSender is on lines 109 - 111.

Within graph, we would need to set the same as Internet Headers such as guidance here. https://learn.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=csharp

E.g.

InternetMessageHeaders = new List<InternetMessageHeader>()
	{
		new InternetMessageHeader
		{
			Name = "Content-Type",
			Value = "text/html"
		},
	}

These would come from IFluentMail.

Hope this helps

**Comment by DavidDeSloovere** [comment]
https://github.com/lukencode/FluentEmail/blob/master/src/Senders/FluentEmail.Smtp/SmtpSender.cs

**Comment by DavidDeSloovere** [comment]
@PS2009DT There is a preview available at https://github.com/ESC-BV/FluentEmail.Graph/pkgs/nuget/FluentEmail.Graph/76099966

**Comment by DavidDeSloovere** [comment]
Will be available shortly on nuget also as v2.3
