### ISSUE TITLE
Set missing properties for FileAttachement and AttachmentItem

### ISSUE THREAD

**Issue by fnuhs** [ESC-BV/FluentEmail.Graph#168]
Hi, we are sending mails with attached images which are referenced in the body via an ContentId.
To get this working i need to have the `ContenId` and `IsInline` Property for `FileAttachment` and `AttachmentItem` set.

GraphSender.cs
`UploadAttachmentUnder3Mb` method:   
```cs
var attachment = new FileAttachment
{
    Name = a.Filename,
    ContentType = a.ContentType,
    ContentBytes = GetAttachmentBytes(a.Data),
    ContentId = a.ContentId,
    IsInline = a.IsInline,

    // can never be bigger than 3MB, so it is save to cast to int
    Size = (int)a.Data.Length,
};
```
+ added set `Size` Property

`UploadAttachment3MbOrOver` method:   
```cs
var attachmentItem = new AttachmentItem
{
    AttachmentType = AttachmentType.File,
    Name = attachment.Filename,
    Size = attachment.Data.Length,
    ContentType = attachment.ContentType,
    ContentId = attachment.ContentId,
    IsInline = attachment.IsInline,
};
```
+ added set `ContentType` Property

I would appreciate if you could add this lines. Or i can provide a PR as well if you like?
Thanks

**Comment by fnuhs** [comment]
#169

**Comment by DavidDeSloovere** [comment]
Thanks @fnuhs 
2.2.0 released 
https://github.com/ESC-BV/FluentEmail.Graph/pkgs/nuget/FluentEmail.Graph
https://www.nuget.org/packages/FluentEmail.Graph/2.2.0 (still indexing at time of writing this)
