### ISSUE TITLE
Upgrade Ms Graph to 5.4

### ISSUE THREAD

**Issue by PS2009DT** [ESC-BV/FluentEmail.Graph#177]
Appreciate if MS Graph can be updated 5.4 version please.

**Comment by DavidDeSloovere** [comment]
@PS2009DT Want to try a pre-release? There is a 2.4.alpha package available on https://github.com/ESC-BV/FluentEmail.Graph/pkgs/nuget/FluentEmail.Graph which includes Microsoft.Graph 5.3

#178

**Comment by PS2009DT** [comment]
Perfect! Thanks for prompt response. Let me give it a play this week.

**Comment by DavidDeSloovere** [comment]
2.4.0 released
