### ISSUE TITLE
Support .NET 8

### ISSUE THREAD

**Issue by AkiraVoid** [ESC-BV/FluentEmail.Graph#231]
I have firstly created an [issue in the main repo of FluentEmail](https://github.com/lukencode/FluentEmail/issues/380), and then I noticed this package is not in the main repo.

To be brief, the older version of Microsoft.Graph does not support .NET 8 which has System.Text.Json 8.0 bundled, and I hope we could upgrade the packages referenced in this project to support .NET 8.

By the way, I also found an [discussion in main repo](https://github.com/lukencode/FluentEmail/discussions/237), written by the author of FluentEmail which is asking you if you want to add the source code into their project.

**Comment by DavidDeSloovere** [comment]
I'm off work for a couple of days, but already want to comment on separate vs one repo: the official repo did not process or publish the PRs, and we needed this feature. The official repo also doesn't seem to update that frequent.

**Comment by AkiraVoid** [comment]
> ...The official repo also doesn't seem to update that frequent.

I agree with you. It seems like they haven't done anything since last year.

**Comment by DavidDeSloovere** [comment]
Does this prerelease work for you?
https://github.com/ESC-BV/FluentEmail.Graph/pkgs/nuget/FluentEmail.Graph/161977902

If yes, I can publish 2.5 on nuget.

**Comment by DavidDeSloovere** [comment]
If forgot how you can add GH as package source. If you don't find it, I can just publish to nuget.

**Comment by AkiraVoid** [comment]
I successfully built my app with the new package.

**Comment by DavidDeSloovere** [comment]
Thanks for confirming.
2.5.0 has been pushed to both:
- the GH nuget and 
- the official nuget.org (still validating at time of writing) https://www.nuget.org/packages/FluentEmail.Graph/2.5.0

Happy holidays.
